/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcDrawer {
        "heading": string;
        "show": boolean;
        "showDrawer": () => Promise<void>;
    }
    interface WcStockFinder {
    }
    interface WcStockPrice {
        "stockSymbol": string;
    }
}
export interface WcStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcStockFinderElement;
}
declare global {
    interface HTMLWcDrawerElement extends Components.WcDrawer, HTMLStencilElement {
    }
    var HTMLWcDrawerElement: {
        prototype: HTMLWcDrawerElement;
        new (): HTMLWcDrawerElement;
    };
    interface HTMLWcStockFinderElement extends Components.WcStockFinder, HTMLStencilElement {
    }
    var HTMLWcStockFinderElement: {
        prototype: HTMLWcStockFinderElement;
        new (): HTMLWcStockFinderElement;
    };
    interface HTMLWcStockPriceElement extends Components.WcStockPrice, HTMLStencilElement {
    }
    var HTMLWcStockPriceElement: {
        prototype: HTMLWcStockPriceElement;
        new (): HTMLWcStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "wc-drawer": HTMLWcDrawerElement;
        "wc-stock-finder": HTMLWcStockFinderElement;
        "wc-stock-price": HTMLWcStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface WcDrawer {
        "heading"?: string;
        "show"?: boolean;
    }
    interface WcStockFinder {
        "onWcSelectedSymbol"?: (event: WcStockFinderCustomEvent<string>) => void;
    }
    interface WcStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "wc-drawer": WcDrawer;
        "wc-stock-finder": WcStockFinder;
        "wc-stock-price": WcStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-drawer": LocalJSX.WcDrawer & JSXBase.HTMLAttributes<HTMLWcDrawerElement>;
            "wc-stock-finder": LocalJSX.WcStockFinder & JSXBase.HTMLAttributes<HTMLWcStockFinderElement>;
            "wc-stock-price": LocalJSX.WcStockPrice & JSXBase.HTMLAttributes<HTMLWcStockPriceElement>;
        }
    }
}
